default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  database: local-election_development

test:
  adapter: postgresql
  database: local-election_test

production:
  heroku: heroku
